---
- name: "Aliases: Configure {{ postfix_alias }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_alias }}"
    regexp: ^\s*{{ item.alias }}\s*:.*$
    line: "{{ item.alias }}: {{ item.user }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ aliases }}"
  notify:
    - newaliases
    - postfix check
    - reload postfix

# EOF
