---

- name: "aliases: Configure {{postfix_alias}}"
  lineinfile:
    dest: "{{postfix_alias}}"
    regexp: "^{{ item.alias }}{{':'}}"
    line: "{{ item.alias }}{{':'}} {{ item.user }}"
    backup: yes
  loop: "{{ aliases }}"
  when: aliases > 0
  notify:
    - newaliases
    - postfix check
    - reload postfix
  tags: postfix_aliases

# EOF
...
