---

- name: "aliases: Configure {{ postfix_alias }}"
  lineinfile:
    dest: "{{ postfix_alias }}"
    regexp: "^{{ item.alias }}{{':'}}"
    line: "{{ item.alias }}{{':'}} {{ item.user }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ aliases }}"
  notify:
    - newaliases
    - postfix check
    - reload postfix

# EOF
...
