---

# Self-signed certificate creation
# http://wiki2.dovecot.org/SSL/CertificateCreation

- name: "certificates: Create directory /etc/ssl/certs"
  ansible.builtin.file:
    state: directory
    path: /etc/ssl/certs
    owner: root
    group: wheel
    mode: "0755"

- name: "certificates: Create directory /etc/ssl/private"
  ansible.builtin.file:
    state: directory
    path: /etc/ssl/private
    owner: root
    group: wheel
    mode: "0700"

- name: "certificates: Chmod 755 /usr/local/share/examples/dovecot/mkcert.sh"
  ansible.builtin.file:
    path: /usr/local/share/examples/dovecot/mkcert.sh
    mode: "0755"
  when: postfix_create_cert|bool

- name: "certificates: Create Self-signed SSL certificates"
  command:
    cmd: >
      sh -c "env OPENSSLCONFIG=/usr/local/share/examples/dovecot/dovecot-openssl.cnf
      /usr/local/share/examples/dovecot/mkcert.sh;
      printf 'dovecot-certificate-changed'"
    creates: /etc/ssl/certs/dovecot.pem
  register: result
  changed_when: result.stdout is search("dovecot-certificate-changed")
  when: postfix_create_cert|bool
  notify:
    - postfix check
    - reload postfix

- name: "certificates: Debug result"
  ansible.builtin.debug:
    var: result
  when: fm_debug|bool

# EOF
...
