---
# Self-signed certificate creation
# http://wiki2.dovecot.org/SSL/CertificateCreation

- name: "Certificates: Create directory /etc/ssl/certs"
  ansible.builtin.file:
    state: directory
    path: /etc/ssl/certs
    owner: root
    group: wheel
    mode: "0755"

- name: "Certificates: Create directory /etc/ssl/private"
  ansible.builtin.file:
    state: directory
    path: /etc/ssl/private
    owner: root
    group: wheel
    mode: "0700"

- name: "Certificates: Chmod 755 /usr/local/share/examples/dovecot/mkcert.sh"
  when: postfix_create_cert | bool
  ansible.builtin.file:
    path: /usr/local/share/examples/dovecot/mkcert.sh
    mode: "0755"

- name: "Certificates: Create Self-signed SSL certificates"
  when: postfix_create_cert | bool
  register: result
  changed_when: result.stdout is search("dovecot-certificate-changed")
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.command:
    cmd: >
      sh -c "env OPENSSLCONFIG=/usr/local/share/examples/dovecot/dovecot-openssl.cnf
      /usr/local/share/examples/dovecot/mkcert.sh;
      printf 'dovecot-certificate-changed'"
    creates: /etc/ssl/certs/dovecot.pem

- name: "Certificates: Debug result fm_debug={{ fm_debug }}"
  when: fm_debug | bool
  ansible.builtin.debug:
    var: result

# EOF
