---
# DO overwrites hostname from rc.conf
- name: "Rcconf: Configure hostname in /etc/rc.digitalocean.d/droplet.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.digitalocean.d/droplet.conf
    regexp: ^{{ item.regexp }}
    line: "{{ item.regexp }}={{ item.line }}"
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: hostname, line: '"{{ rc_conf_hostname }}"' }
  when:
    - digitalocean|bool
    - ansible_distribution_major_version is version('11', '<')
  tags: fm-cloud-do

# EOF
