---

- name: "dkim: Debug"
  ansible.builtin.debug:
    var: fm_dkim_domains
  when: fm_debug|bool
  tags: fm-dkim-debug

- name: "dkim: Create DKIM keys"
  ansible.builtin.command:
    cmd: "opendkim-genkey -r -s {{ item.selector }} -d {{ item.name }} -D {{ fm_dkim_dir_keys }}/{{ item.name }}"
    creates: "{{ fm_dkim_dir_keys }}/{{ item.name }}/default.txt"
  loop: "{{ fm_dkim_domains }}"
  loop_control:
    label: "{{ item.selector }} {{ item.name }}"
  when: fm_dkim_create_keys|bool
  notify: verify dkim
  tags: fm-dkim-create-keys

- name: "dkim: Set ownership and permissions of DKIM private keys"
  ansible.builtin.file:
    path: "{{ fm_dkim_dir_keys }}/{{ item.name }}/{{ item.selector }}.private"
    owner: "{{ fm_dkim_milteropendkim_uid }}"
    group: "{{ fm_dkim_milteropendkim_gid }}"
    mode: "{{ fm_dkim_private_key_mode }}"
  loop: "{{ fm_dkim_domains }}"
  loop_control:
    label: "{{ item.selector }} {{ item.name }}"
  when: not ansible_check_mode
  tags: fm-dkim-keys-private-mod

- name: "dkim: Set ownership and permissions of DKIM public keys"
  ansible.builtin.file:
    path: "{{ fm_dkim_dir_keys }}/{{ item.name }}/{{ item.selector }}.txt"
    owner: "{{ fm_dkim_milteropendkim_uid }}"
    group: "{{ fm_dkim_milteropendkim_gid }}"
    mode: "{{ fm_dkim_public_key_mode }}"
  loop: "{{ fm_dkim_domains }}"
  loop_control:
    label: "{{ item.selector }}/{{ item.name }}"
  when: not ansible_check_mode
  tags: fm-dkim-keys-public-mod

- name: "dkim: Create {{ fm_dkim_dir }}/TrustedHosts"
  ansible.builtin.template:
    src: TrustedHosts.j2
    dest: "{{ fm_dkim_dir }}/TrustedHosts"
    mode: "0644"
  notify: verify dkim
  when: fm_dkim_create_trusted_hosts|bool
  tags: fm-dkim-create-TrustedHosts

- name: "dkim: Create {{ fm_dkim_dir }}/SigningTable"
  ansible.builtin.template:
    src: SigningTable.j2
    dest: "{{ fm_dkim_dir }}/SigningTable"
    mode: "0644"
  notify: verify dkim
  when: fm_dkim_create_signingtable|bool
  tags: fm-dkim-create-SigningTable

- name: "dkim: Create {{ fm_dkim_dir }}/KeyTable"
  ansible.builtin.template:
    src: KeyTable.j2
    dest: "{{ fm_dkim_dir }}/KeyTable"
    mode: "0644"
  notify: verify dkim
  when: fm_dkim_create_keytable|bool
  tags: fm-dkim-create-KeyTable

- name: "dkim: Set ownership and permissions of DKIM run dir"
  ansible.builtin.file:
    state: directory
    path: "{{ fm_dkim_run_dir }}"
    owner: "{{ fm_dkim_milteropendkim_uid }}"
    group: "{{ fm_dkim_milteropendkim_gid }}"
    mode: "0750"
  tags: fm-dkim-run

- name: "dkim: Configure {{ fm_dkim_conf_path }}"
  ansible.builtin.lineinfile:
    dest: "{{ fm_dkim_conf_path }}"
    regexp: '^\s*{{ item.regexp }}\s+(.*)$'
    line: "{{ item.regexp }} {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
    create: true
    mode: "0644"
  loop: "{{ fm_dkim_conf }}"
  notify: verify dkim
  tags: fm-dkim-conf

# EOF
...
