---

# example conf
- name: "dovecot: Copy example conf to /usr/local/etc/dovecot/"
  shell: cd /usr/local/etc/dovecot && cp -R example-config/{{ item }} .
  args:
    creates: /usr/local/etc/dovecot/{{ item }}
  with_items:
    - conf.d
    - dovecot-dict-auth.conf.ext
    - dovecot-dict-sql.conf.ext
    - dovecot-ldap.conf.ext
    - dovecot-sql.conf.ext
    - dovecot.conf
  tags: dovecot_example_conf

# dovecot.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/dovecot.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/dovecot.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  with_items: "{{ dovecot_conf }}"
  notify: reload dovecot
  tags: dovecot_conf

# conf.d/10-master.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/10-master.conf"
  blockinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-master.conf"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "Postfix smtp-auth"
    block: |
      unix_listener /var/spool/postfix/private/auth {
      mode = 0660
      user = postfix
      group = postfix
      }
  notify: reload dovecot
  tags: dovecot_master_conf

# create #ssl_dh
- name: "dovecot: Create {{ dovecot_ssl_dh }}"
  command: "openssl dhparam -out {{ dovecot_ssl_dh }} 4096"
  args:
    creates: "{{ dovecot_ssl_dh }}"
  tags: dovecot_ssl_dh

# conf.d/10-ssl.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/10-ssl.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-ssl.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  with_items: "{{ dovecot_ssl_conf }}"
  notify: reload dovecot
  tags: dovecot_ssl_conf

# conf.d/10-mail.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/10-mail.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-mail.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  with_items: "{{ dovecot_mail_conf }}"
  notify: reload dovecot
  tags: dovecot_mail_conf

# conf.d/10-auth.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/10-auth.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-auth.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  with_items: "{{ dovecot_auth_conf }}"
  notify: reload dovecot
  tags: dovecot_auth_conf

# conf.d/10-logging.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/10-logging.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-logging.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  with_items: "{{ dovecot_logging_conf }}"
  notify: reload dovecot
  tags: dovecot_logging_conf

# conf.d/15-lda.conf
- name: "dovecot: Configure /usr/local/etc/dovecot/conf.d/15-lda.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/15-lda.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    insertafter: "protocol lda {"
    backup: yes
  with_items: "{{ dovecot_lda_conf }}"
  notify: reload dovecot
  tags: dovecot_lda_conf

# conf.d/15-mailboxes.conf
#- name: Configure /usr/local/etc/dovecot/conf.d/15-mailboxes.conf
#  lineinfile: dest=/usr/local/etc/dovecot/conf.d/15-mailboxes.conf regexp="{{ item.regexp }}" line="{{ item.line }}" backup="yes"
#  with_items:
#    - { regexp: "^",  line: ""}
#  notify: reload dovecot
#  tags: config_dovecot_mailboxes

# EOF
...
