---
# tasks for freebsd-mailserver

- import_tasks: debug.yml
  when: fm_debug|bool
  tags: [fm-debug, always]

- import_tasks: packages.yml
  tags: fm-packages

- import_tasks: sanity.yml
  when: fm_sanity|bool
  tags: fm-sanity

- import_tasks: files.yml
  tags: fm-files

- import_tasks: certificates.yml
  tags: fm-certificates

- import_tasks: rcconf.yml
  tags: fm-rcconf

- import_tasks: cloud_provider.yml
  tags: fm-cloud

- import_tasks: mailer_conf.yml
  tags: fm-mailer_conf

- import_tasks: periodic_conf.yml
  tags: fm-periodic_conf

- import_tasks: postfix.yml
  tags: fm-postfix

- import_tasks: postfix_sasl.yml
  tags: fm-postfix_sasl

- import_tasks: postfix_master.yml
  tags: fm-postfix_master

- import_tasks: virtual_aliases.yml
  tags: fm-virtual_aliases

- import_tasks: aliases.yml
  tags: fm-aliases

- import_tasks: dovecot.yml
  tags: fm-dovecot

# EOF
...
