---
- name: "Packages: Install packages flavor"
  register: result
  community.general.pkgng:
    name: "{{ freebsd_mailserver_packages_flavor }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

- name: "Packages: Install packages"
  when: freebsd_install_method | lower == 'packages'
  register: result
  community.general.pkgng:
    name: "{{ freebsd_mailserver_packages }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

- name: "Packages: Install ports"
  when: freebsd_install_method|lower == 'ports'
  register: result
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ freebsd_mailserver_packages }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

# EOF
