---
- name: "Pam: Debug fm_debug={{ fm_debug }}"
  when: fm_debug | bool
  tags: fm-pam-debug
  ansible.builtin.debug:
    var: fm_pam_conf

- name: "Pam: Configure pam"
  tags: fm-pam-conf
  ansible.builtin.template:
    src: pam.j2
    dest: "/etc/pam.d/{{ item.key }}"
    mode: "0644"
  loop: "{{ fm_pam_conf | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

# EOF
