---

# smtpd sasl
- name: "postfix_sasl: Configure SASL {{postfix_main_cf}}"
  lineinfile:
    dest: "{{postfix_main_cf}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    backup: yes
  loop: "{{ postfix_main_cf_smtpd_sasl_conf }}"
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtpd_sasl

# smtp sasl
- name: "postfix_sasl: Enable SASL {{ postfix_main_cf }}"
  lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  loop: "{{ postfix_main_cf_smtp_sasl_enable_conf }}"
  when: postfix_main_cf_smtp_sasl_auth_enable
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_enable

- name: "postfix_sasl: Disable SASL {{ postfix_main_cf }}"
  lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  loop: "{{ postfix_main_cf_smtp_sasl_disable_conf }}"
  when: not postfix_main_cf_smtp_sasl_auth_enable
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_disable

# smtp_sasl_password_maps
- name: "postfix_sasl: Configure smtp_sasl_password_maps {{ postfix_main_cf }}"
  lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: "^smtp_sasl_password_maps"
    line: "smtp_sasl_password_maps = hash:{{ postfix_main_cf_smtp_sasl_password_maps }}"
    backup: yes
  when:
    - not "postfix_main_cf_smtp_sasl_password_maps" | trim == ""
    - postfix_main_cf_smtp_sasl_auth_enable
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_password_maps

# smtp_sasl_passwords
- name: "postfix_sasl: Configure smtp_sasl_password_maps {{ postfix_main_cf_smtp_sasl_password_maps }}"
  lineinfile:
    dest: "{{ postfix_main_cf_smtp_sasl_password_maps }}"
    regexp: "{{ item.relayhost }}"
    line: "{{ item.line }}"
    owner: "root"
    group: "wheel"
    mode: "0640"
    backup: yes
    create: yes
  loop: "{{ postfix_smtp_sasl_passwords }}"
  notify:
    - postmap smtp sasl passwords
    - postfix check
    - reload postfix
  tags: postfix_smtp_sasl_passwords

# EOF
...
