---

# main.cf
- name: "postfix: Configure {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_conf }}"
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf

# mydestination pcre file (optional)
- name: "postfix: Create pcre {{ postfix_main_cf_mydestination_pcre_file }}"
  ansible.builtin.template:
    src: mydestinations.j2
    dest: "{{ postfix_main_cf_mydestination_pcre_file }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fm_backup_conf }}"
  notify:
    - postfix check
    - reload postfix
  when: postfix_main_cf_mydestination_pcre|length > 0
  tags: postfix_main_cf_mydestination_pcre

# mydestination pcre (optional)
- name: "postfix: Configure pcre mydestination in {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*mydestination\s*=(.*)$'
    line: "mydestination = pcre:{{ postfix_main_cf_mydestination_pcre_file }}"
    backup: "{{ fm_backup_conf }}"
  notify:
    - postfix check
    - reload postfix
  when: postfix_main_cf_mydestination_pcre|length > 0
  tags: postfix_main_cf_mydestination_pcre

# mydestination (no pcre)
- name: "postfix: Configure mydestination in {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*mydestination\s*=(.*)$'
    line: "mydestination = {{ postfix_main_cf_mydestination }}"
    backup: "{{ fm_backup_conf }}"
  notify:
    - postfix check
    - reload postfix
  when: postfix_main_cf_mydestination_pcre|length == 0
  tags: postfix_main_cf_mydestination

# relayhost
- name: "postfix: Configure relayhost in {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*relayhost\s*=(.*)$'
    line: "relayhost = {{ postfix_main_cf_relayhost }}"
    backup: "{{ fm_backup_conf }}"
  when: postfix_main_cf_relayhost|length > 0
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_relayhost

# virtual domains
- name: "postfix: Configure Virtual Domains {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_virtual_alias_maps_conf }}"
  notify:
    - postmap virtual aliases
    - postfix check
    - reload postfix
  tags: postfix_main_cf_virtual_domains

# smtpd
- name: "postfix: Configure SMTPD {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtpd_conf }}"
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtpd

# smtp
- name: "postfix: Configure SMTP {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtp_conf }}"
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp

# EOF
...
