---
# main.cf
- name: "Postfix: Configure {{ postfix_main_cf }}"
  tags: postfix_main_cf
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_conf }}"

# mydestination pcre file (optional)
- name: "Postfix: Create pcre {{ postfix_main_cf_mydestination_pcre_file }}"
  when: postfix_main_cf_mydestination_pcre | length > 0
  tags: postfix_main_cf_mydestination_pcre
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.template:
    src: mydestinations.j2
    dest: "{{ postfix_main_cf_mydestination_pcre_file }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fm_backup_conf }}"

# mydestination pcre (optional)
- name: "Postfix: Configure pcre mydestination in {{ postfix_main_cf }}"
  when: postfix_main_cf_mydestination_pcre | length > 0
  tags: postfix_main_cf_mydestination_pcre
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*mydestination\s*=(.*)$
    line: mydestination = pcre:{{ postfix_main_cf_mydestination_pcre_file }}
    backup: "{{ fm_backup_conf }}"

# mydestination (no pcre)
- name: "Postfix: Configure mydestination in {{ postfix_main_cf }}"
  when: postfix_main_cf_mydestination_pcre | length == 0
  tags: postfix_main_cf_mydestination
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*mydestination\s*=(.*)$
    line: mydestination = {{ postfix_main_cf_mydestination }}
    backup: "{{ fm_backup_conf }}"

# relayhost
- name: "Postfix: Configure relayhost in {{ postfix_main_cf }}"
  when: postfix_main_cf_relayhost|length > 0
  tags: postfix_main_cf_relayhost
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*relayhost\s*=(.*)$
    line: relayhost = {{ postfix_main_cf_relayhost }}
    backup: "{{ fm_backup_conf }}"

# virtual domains
- name: "Postfix: Configure Virtual Domains {{ postfix_main_cf }}"
  tags: postfix_main_cf_virtual_domains
  notify:
    - postmap virtual aliases
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_virtual_alias_maps_conf }}"

# smtpd
- name: "Postfix: Configure SMTPD {{ postfix_main_cf }}"
  tags: postfix_main_cf_smtpd
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtpd_conf }}"

# smtp
- name: "Postfix: Configure SMTP {{ postfix_main_cf }}"
  tags: postfix_main_cf_smtp
  notify:
    - postfix check
    - reload postfix
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtp_conf }}"

# EOF
