---

# smtpd sasl
- name: "postfix_sasl: Configure SASL {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtpd_sasl_conf }}"
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtpd_sasl

# smtp sasl
- name: "postfix_sasl: Enable SASL {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtp_sasl_enable_conf }}"
  when: postfix_main_cf_smtp_sasl_auth_enable|bool
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_enable

- name: "postfix_sasl: Disable SASL {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: "{{ fm_backup_conf }}"
  loop: "{{ postfix_main_cf_smtp_sasl_disable_conf }}"
  when: not postfix_main_cf_smtp_sasl_auth_enable|bool
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_disable

# smtp_sasl_password_maps
- name: "postfix_sasl: Configure smtp_sasl_password_maps in {{ postfix_main_cf }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_main_cf }}"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "smtp_sasl_password_maps = hash:{{ postfix_main_cf_smtp_sasl_password_maps }}"
    backup: "{{ fm_backup_conf }}"
  when:
    - postfix_main_cf_smtp_sasl_password_maps|length > 0
    - postfix_main_cf_smtp_sasl_auth_enable|bool
  notify:
    - postfix check
    - reload postfix
  tags: postfix_main_cf_smtp_sasl_password_maps

# smtp_sasl_passwords
- name: "postfix_sasl: Create {{ postfix_main_cf_smtp_sasl_password_maps }}"
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: "{{ postfix_main_cf_smtp_sasl_password_maps }}"
    owner: root
    group: wheel
    mode: "0640"
    backup: "{{ fm_backup_conf }}"
  notify:
    - postmap smtp sasl passwords
    - postfix check
    - reload postfix
  tags: postfix_smtp_sasl_passwd_create

# EOF
...
