---
- name: "Rcconf: Configure hostname in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: hostname, value: "{{ rc_conf_hostname }}" }
  notify: set hostname
  tags: fm-rcconf-hostname

- name: "Rcconf: Disable sendmail in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: sendmail_enable, value: NONE }
    - { regexp: sendmail_submit_enable, value: "NO" }
    - { regexp: sendmail_outbound_enable, value: "NO" }
    - { regexp: sendmail_msp_queue_enable, value: "NO" }
  when: fm_postfix_enable|bool
  notify: stop sendmail
  tags: fm-rcconf-postfix

- name: "Rcconf: Enable and Start Postfix"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: postfix_enable, value: "YES" }
  when: fm_postfix_enable|bool
  notify:
    - postfix check
    - enable and start postfix
  tags: fm-rcconf-postfix

- name: "Rcconf: Enable and Start Dovecot"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: dovecot_enable, value: "YES" }
  when: fm_dovecot_enable|bool
  notify: enable and start dovecot
  tags: fm-rcconf-dovecot

- name: "Rcconf: Enable and Start DKIM"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: milteropendkim_enable, value: "YES" }
  when: fm_dkim_enable|bool
  notify: enable and start dkim
  tags: fm-rcconf-dkim

- name: "Rcconf: Disable and Stop Dovecot"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: dovecot_enable, value: "NO" }
  when: not fm_dovecot_enable|bool
  notify: disable and stop dovecot
  tags: fm-rcconf-dovecot

- name: "Rcconf: Disable and Stop DKIM"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - { regexp: milteropendkim_enable, value: "NO" }
  when: not fm_dkim_enable|bool
  notify: disable and stop dkim
  tags: fm-rcconf-dkim

- name: "Rcconf: Configure Postfix"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop: "{{ fm_postfix_rcconf }}"
  notify: reload postfix
  tags: fm-rcconf-postfix

- name: "Rcconf: Configure Dovecot"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop: "{{ fm_dovecot_rcconf }}"
  notify: reload dovecot
  tags: fm-rcconf-dovecot

- name: "Rcconf: Configure DKIM"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop: "{{ fm_dkim_rcconf }}"
  notify: reload dkim
  tags: fm-rcconf-dkim

- name: "rcconf: Enable sendmail in /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop:
    - {regexp: sendmail_enable, value: "YES"}
  when: fm_sendmail_enable|bool
  notify: start sendmail
  tags: fm-rcconf-sendmail

- name: "rcconf: Configure SpamAssassin"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_backup_conf }}"
  loop: "{{ fm_sa_rcconf }}"
  when: fm_sa_enable|bool
  notify: restart SpamAssassin
  tags: fm-rcconf-sa

# EOF
