---

- name: "rcconf: Configure hostname in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "^hostname", line: "hostname=\"{{rc_conf_hostname}}\""}
  notify: set hostname
  tags: postfix_rcconf_hostname

- name: "rcconf: Disable sendmail in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "^sendmail_enable", line: "sendmail_enable=\"NONE\""}
    - { regexp: "^sendmail_submit_enable", line: "sendmail_submit_enable=\"NO\""}
    - { regexp: "^sendmail_outbound_enable", line: "sendmail_outbound_enable=\"NO\""}
    - { regexp: "^sendmail_msp_queue_enable", line: "sendmail_msp_queue_enable=\"NO\""}
  notify: stop sendmail
  tags: postfix_rcconf_sendmail

- name: "rcconf: Enable postfix and dovecot in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "^postfix_enable", line: "postfix_enable=\"YES\""}
    - { regexp: "^dovecot_enable", line: "dovecot_enable=\"YES\""}
  tags: postfix_rcconf_postfix

# DO overwrites hostname from rc.conf
- name: "rcconf: Configure hostname in /etc/rc.digitalocean.d/droplet.conf"
  lineinfile:
    dest: "/etc/rc.digitalocean.d/droplet.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "^hostname", line: "hostname=\"{{rc_conf_hostname}}\""}
  when:
    - digitalocean
    - ansible_distribution_major_version < '11'
  tags: postfix_rcconf_digitalocean

# EOF
...
