---

- name: "rcconf: Configure hostname in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: "^hostname", line: "hostname=\"{{rc_conf_hostname}}\"" }
  notify: set hostname
  tags: postfix_rcconf_hostname

- name: "rcconf: Disable sendmail in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: "^sendmail_enable", line: "sendmail_enable=\"NONE\"" }
    - { regexp: "^sendmail_submit_enable", line: "sendmail_submit_enable=\"NO\"" }
    - { regexp: "^sendmail_outbound_enable", line: "sendmail_outbound_enable=\"NO\"" }
    - { regexp: "^sendmail_msp_queue_enable", line: "sendmail_msp_queue_enable=\"NO\"" }
  notify: stop sendmail
  tags: postfix_rcconf_sendmail

- name: "rcconf: Enable and Start Postfix"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: yes
  loop:
    - { regexp: "postfix_enable", line: "\"YES\"" }
  when: fm_postfix_enable
  notify:
    - postfix check
    - enable and start postfix
  tags: postfix_rcconf_postfix

- name: "rcconf: Enable and Start Dovecot"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: yes
  loop:
    - { regexp: "dovecot_enable", line: "\"YES\"" }
  when: fm_dovecot_enable
  notify: enable and start dovecot
  tags: postfix_rcconf_dovecot

- name: "rcconf: Disable and Stop Postfix"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: yes
  loop:
    - { regexp: "postfix_enable", line: "\"NO\"" }
  when: not fm_postfix_enable
  notify: disable and stop postfix
  tags: postfix_rcconf_postfix

- name: "rcconf: Disable and Stop Dovecot"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: yes
  loop:
    - { regexp: "dovecot_enable", line: "\"NO\"" }
  when: not fm_dovecot_enable
  notify: disable and stop dovecot
  tags: postfix_rcconf_dovecot

# DO overwrites hostname from rc.conf
- name: "rcconf: Configure hostname in /etc/rc.digitalocean.d/droplet.conf"
  lineinfile:
    dest: "/etc/rc.digitalocean.d/droplet.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: "^hostname", line: "hostname=\"{{rc_conf_hostname}}\"" }
  when:
    - digitalocean
    - ansible_distribution_major_version < '11'
  tags: postfix_rcconf_digitalocean

# EOF
...
