---

- name: "virtual_aliases: Configure virtual aliases {{ postfix_virtual }}"
  ansible.builtin.lineinfile:
    dest: "{{ postfix_virtual }}"
    regexp: '^\s*{{ item.alias }}(?!\S).*$'
    line: "{{ item.alias }}\t {{ item.user }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fm_backup_conf }}"
    create: true
  loop: "{{ virtual_aliases }}"
  notify:
    - postmap virtual aliases
    - postfix check
    - reload postfix

# EOF
...
