---
# handlers for freebsd-mailserver

- name: newaliases
  block:
    - command: "/usr/local/sbin/postfix check"
    - command: "/usr/bin/newaliases"

- name: postmap smtp sasl passwords
  block:
    - command: "/usr/local/sbin/postfix check"
    - command: "/usr/local/sbin/postmap {{postfix_main_cf_smtp_sasl_password_maps}}"

- name: postmap virtual aliases
  block:
    - command: "/usr/local/sbin/postfix check"
    - command: "/usr/local/sbin/postmap {{postfix_virtual}}"

- name: set hostname
  block:
    - command: "/usr/local/sbin/postfix check"
    - command: "/bin/hostname {{rc_conf_hostname}}"

- name: reload postfix
  block:
    - command: "/usr/local/sbin/postfix check"
    - service:
        name: "postfix"
        state: "reloaded"

- name: restart postfix
  block:
    - command: "/usr/local/sbin/postfix check"
    - service:
        name: "postfix"
        state: "restarted"

- name: reload dovecot
  block:
    - command: "/usr/local/sbin/postfix check"
    - service:
        name: "dovecot"
        state: "reloaded"

- name: restart dovecot
  block:
    - command: "/usr/local/sbin/postfix check"
    - service:
        name: "dovecot"
        state: "restarted"

- name: stop sendmail
  block:
    - command: "/usr/local/sbin/postfix check"
    - service:
        name: "sendmail"
        state: "stopped"

# EOF
