---
# handlers for freebsd_mailserver

- name: Postfix check # noqa: no-changed-when
  listen: postfix check
  ansible.builtin.command:
    cmd: /usr/local/sbin/postfix check

- name: Newaliases # noqa: no-changed-when
  listen: newaliases
  ansible.builtin.command:
    cmd: /usr/bin/newaliases

- name: Postmap smtp sasl passwords # noqa: no-changed-when
  listen: postmap smtp sasl passwords
  ansible.builtin.command:
    cmd: /usr/local/sbin/postmap {{ postfix_main_cf_smtp_sasl_password_maps }}

- name: Postmap virtual aliases # noqa: no-changed-when
  listen: postmap virtual aliases
  ansible.builtin.command:
    cmd: /usr/local/sbin/postmap {{ postfix_virtual }}

- name: Set hostname # noqa: no-changed-when
  listen: set hostname
  ansible.builtin.command:
    cmd: /bin/hostname {{ rc_conf_hostname }}

# Postfix

- name: Enable and start postfix
  listen: enable and start postfix
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true

- name: Disable and stop postfix
  listen: disable and stop postfix
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false

- name: Reload postfix
  listen: reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded
  when: fm_postfix_enable | bool

- name: Restart postfix
  listen: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: fm_postfix_enable | bool

# Dovecot

- name: Enable and start dovecot
  listen: enable and start dovecot
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true

- name: Disable and stop dovecot
  listen: disable and stop dovecot
  ansible.builtin.service:
    name: dovecot
    state: stopped
    enabled: false

- name: Reload dovecot
  listen: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  when: fm_dovecot_enable | bool

- name: Restart dovecot
  listen: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
  when: fm_dovecot_enable | bool

# Sendmail

- name: restart sendmail
  ansible.builtin.service:
    name: sendmail
    state: restarted
  when: fm_sendmail_enable|bool

- name: start sendmail
  ansible.builtin.service:
    name: sendmail
    state: started

- name: Stop sendmail
  listen: stop sendmail
  ansible.builtin.service:
    name: sendmail
    state: stopped

- name: Update access
  ansible.builtin.shell:
  args:
    cmd: "/usr/sbin/makemap hash {{ sendmail_access_file }} < {{ sendmail_access_file }}"
    chdir: "{{ fm_sendmail_dir }}"

- name: Update genericstable
  ansible.builtin.shell:
  args:
    cmd: "/usr/sbin/makemap hash {{ sendmail_genericstable_file }} < {{ sendmail_genericstable_file }}"
    chdir: "{{ fm_sendmail_dir }}"

- name: Update mailertable
  ansible.builtin.shell:
  args:
    cmd: "/usr/sbin/makemap hash {{ sendmail_mailertable_file }} < {{ sendmail_mailertable_file }}"
    chdir: "{{ fm_sendmail_dir }}"

- name: Update virtusertable
  ansible.builtin.shell:
  args:
    cmd: "/usr/sbin/makemap hash {{ sendmail_virtusertable_file }} < {{ sendmail_virtusertable_file }}"
    chdir: "{{ fm_sendmail_dir }}"

- name: Update sendmail.cf
  ansible.builtin.command:
    cmd: "/usr/bin/make {{ fm_sendmail_cf_file }}"
    chdir: "{{ fm_sendmail_dir }}"
  notify: restart sendmail

# DKIM

- name: Enable and start dkim
  listen: enable and start dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: started
    enabled: true

- name: Disable and stop dkim
  listen: disable and stop dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: stopped
    enabled: false

- name: Reload dkim
  listen: reload dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: reloaded
  when: fm_dkim_enable | bool

- name: Restart dkim
  listen: restart dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: restarted
  when: fm_dkim_enable | bool

# Milter regex

- name: enable and start milter-regex
  ansible.builtin.service:
    name: milterregex
    state: started
    enabled: true
  when: fm_milter_regex_enable|bool
   
- name: disable and stop milter-regex
  ansible.builtin.service:
    name: milterregex
    state: stopped
    enabled: false
  when: fm_milter_regex_enable|bool
   
- name: restart milter-regex
  ansible.builtin.service:
    name: milterregex
    state: restarted
  when: fm_milter_regex_enable|bool
   
- name: verify milter-regex
  ansible.builtin.command:
    cmd: "{{ fm_milter_regex_bin }} -t -c {{ fm_milter_regex_cf_file }}"
  when: fm_milter_regex_enable|bool
  notify: restart milter-regex

# EOF
