---
# handlers for freebsd_mailserver

- name: postfix check
  ansible.builtin.command:
    cmd: /usr/local/sbin/postfix check

- name: newaliases
  ansible.builtin.command:
    cmd: /usr/bin/newaliases

- name: postmap smtp sasl passwords
  ansible.builtin.command:
    cmd: "/usr/local/sbin/postmap {{ postfix_main_cf_smtp_sasl_password_maps }}"

- name: postmap virtual aliases
  ansible.builtin.command:
    cmd: "/usr/local/sbin/postmap {{ postfix_virtual }}"

- name: set hostname
  ansible.builtin.command:
    cmd: "/bin/hostname {{ rc_conf_hostname }}"

# Postfix

- name: enable and start postfix
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true

- name: disable and stop postfix
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: false

- name: reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded
  when: fm_postfix_enable|bool

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: fm_postfix_enable|bool

# Dovecot

- name: enable and start dovecot
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true

- name: disable and stop dovecot
  ansible.builtin.service:
    name: dovecot
    state: stopped
    enabled: false

- name: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  when: fm_dovecot_enable|bool

- name: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
  when: fm_dovecot_enable|bool

# Sendmail

- name: stop sendmail
  ansible.builtin.service:
    name: sendmail
    state: stopped

# DKIM

- name: enable and start dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: started
    enabled: true

- name: disable and stop dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: stopped
    enabled: false

- name: reload dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: reloaded
  when: fm_dkim_enable|bool

- name: restart dkim
  ansible.builtin.service:
    name: milter-opendkim
    state: restarted
  when: fm_dkim_enable|bool

# EOF
...
