---
# handlers for freebsd-mailserver

- name: postfix check
  command: "/usr/local/sbin/postfix check"

- name: newaliases
  command: "/usr/bin/newaliases"

- name: postmap smtp sasl passwords
  command: "/usr/local/sbin/postmap {{postfix_main_cf_smtp_sasl_password_maps}}"

- name: postmap virtual aliases
  command: "/usr/local/sbin/postmap {{postfix_virtual}}"

- name: set hostname
  command: "/bin/hostname {{rc_conf_hostname}}"

- name: enable and start postfix
  service:
    name: "postfix"
    state: "started"
    enabled: yes

- name: disable and stop postfix
  service:
    name: "postfix"
    state: "stopped"
    enabled: no

- name: reload postfix
  service:
    name: "postfix"
    state: "reloaded"

- name: restart postfix
  service:
    name: "postfix"
    state: "restarted"

- name: enable and start dovecot
  service:
    name: "dovecot"
    state: "started"
    enabled: yes

- name: disable and stop dovecot
  service:
    name: "dovecot"
    state: "stopped"
    enabled: no

- name: reload dovecot
  service:
    name: "dovecot"
    state: "reloaded"

- name: restart dovecot
  service:
    name: "dovecot"
    state: "restarted"

- name: stop sendmail
  service:
    name: "sendmail"
    state: "stopped"

# EOF
...
