---
# handlers for freebsd-mailserver

- name: postfix check
  command: "/usr/local/sbin/postfix check"

- name: newaliases
  command: "/usr/bin/newaliases"

- name: postmap smtp sasl passwords
  command: "/usr/local/sbin/postmap {{ postfix_main_cf_smtp_sasl_password_maps }}"

- name: postmap virtual aliases
  command: "/usr/local/sbin/postmap {{ postfix_virtual }}"

- name: set hostname
  command: "/bin/hostname {{ rc_conf_hostname }}"

- name: enable and start postfix
  service:
    name: "postfix"
    state: started
    enabled: true

- name: disable and stop postfix
  service:
    name: "postfix"
    state: stopped
    enabled: false

- name: reload postfix
  service:
    name: "postfix"
    state: reloaded
  when: fm_postfix_enable|bool

- name: restart postfix
  service:
    name: "postfix"
    state: restarted
  when: fm_postfix_enable|bool

- name: enable and start dovecot
  service:
    name: "dovecot"
    state: started
    enabled: true

- name: disable and stop dovecot
  service:
    name: "dovecot"
    state: stopped
    enabled: false

- name: reload dovecot
  service:
    name: "dovecot"
    state: reloaded
  when: fm_dovecot_enable|bool

- name: restart dovecot
  service:
    name: "dovecot"
    state: restarted
  when: fm_dovecot_enable|bool

- name: stop sendmail
  service:
    name: "sendmail"
    state: stopped

# EOF
...
